### ISSUE TITLE
Cluster and Profile ids are read wrongly when building a 0x11 Frame

### ISSUE THREAD

**Issue by marianofino** [jankolkmeier/xbee-api#44]
Given the following frame (taken from the README):
```
var XBeeAPI = require('xbee-api').XBeeAPI;

var xbeeAPI = new XBeeAPI({
  api_mode: 1
});

var frame = xbeeAPI.buildFrame({
    type: 0x11, // xbee_api.constants.FRAME_TYPE.ZIGBEE_TRANSMIT_REQUEST
    id: 0x01, // optional, nextFrameId() is called per default
    destination64: "0013a200400a0127", // default is broadcast address
    destination16: "fffe", // default is "fffe" (unknown/broadcast)
    sourceEndpoint: 0xA0,
    destinationEndpoint: 0xA1,
    clusterId: "1554",
    profileId: "C105",
    broadcastRadius: 0x00, // optional, 0x00 is default
    options: 0x00, // optional, 0x00 is default
    data: "TxData0A" // Can either be string or byte array.
})
```

The expected cluster is 0x1554 with profile 0xC105. However the actual output cluster is 0x0612 with profile 0x0000.

If only strings are accepted for these parameters, a fixed could be changing these lines:
```
builder.appendUInt16BE(frame.clusterId);
builder.appendUInt16BE(frame.profileId);
```
for these ones:
```
builder.appendString(frame.clusterId, 'hex');
builder.appendString(frame.profileId, 'hex');
```

Thank you

**Comment by jankolkmeier** [comment]
Thank you for spotting this!
Your proposed change in fact works both for byte arrays as well as for strings.

Curiously, the current implementation only works if the value is specified as a number (i.e. clusterId: 0x1554). So this is certainly documented incorrectly.

I don't remember what the reason was to not support 'number' format for other 16bit parameters. It seems more intuitive than both byte array and strings. It might have been consistence over convenience, since buffer-builder doesn't support an appendUInt16BE equivalent for 64bit parameters (such as the 64bit addresses for newer firmwares). 

I think the way to address this is first taking your suggested fix, while keeping a check for the 'number' type to revert to the previous implementation (so not to break anything for those that already worked around this). Supporting the number-style parameter officially also for different frame types is something to look at in the future.
